name: Job Alerts Bot

on:
  schedule:
    - cron: "0 * * * *"  # runs every hour
  workflow_dispatch:     # allows manual run

jobs:
  scrape_and_alert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4

    - name: Run job scraper
      env:
        GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      run: |
        python jobscraper.py
